name: kp2024
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  carousel_slider: ^4.0.0
  table_calendar: ^3.0.9
  file_picker: ^4.0.0
  shared_preferences: ^2.0.6
  intl: ^0.18.0
  provider: ^6.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  yaml: ^3.1.2
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  universal_html: ^2.2.4
  flutter_cached_pdfview: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/LogoISO.png
    - images/LogoUdinus.png
    - images/comp.jpg
    - images/anis.png
    - images/prabowo.png
    - images/ganjar.png
    - images/LogoLab.png
    - images/iconLokasi.png
    - images/iconTelepon.png
    - images/iconEmail.png
    - images/iconInstagram.png
    - images/iconWhatsapp.png
    - images/iconWhatsappWarna.png
    - images/iconFacebook.png
    - images/iconPerson.png
    - images/wallpaper.png
    - images/gambar.jpg
    - images/BerhasildiBooked.png
    - .env

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-VariableFont_wght.ttf
          weight: 700
    - family: Archivo
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf
          weight: 700